import mongoose from "mongoose";
import dotenv from "dotenv";
import Category from "../models/Category.js";
import Product from "../models/Product.js";
import { seedCombos } from "./comboSeeder.js";

dotenv.config();

const CATEGORIES = [
  {
    name: "Áo",
    slug: "ao",
    description: "Áo thun, áo sơ mi, áo polo và các loại áo nam",
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop",
  },
  {
    name: "Quần",
    slug: "quan",
    description: "Quần jeans, quần cargo, quần kaki và các loại quần nam",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=800&auto=format&fit=crop",
  },
  {
    name: "Hoodie & Sweater",
    slug: "hoodie-sweater",
    description: "Hoodie, sweater, áo khoác nỉ giữ ấm phong cách",
    image: "https://images.unsplash.com/photo-1619603364904-c0498317e145?q=80&w=800&auto=format&fit=crop",
  },
  {
    name: "Phụ kiện",
    slug: "phu-kien",
    description: "Balo, túi, mũ, thắt lưng và phụ kiện thời trang nam",
    image: "https://images.unsplash.com/photo-1581605405669-fcdf81165afa?q=80&w=800&auto=format&fit=crop",
  },
  {
    name: "Giày",
    slug: "giay",
    description: "Giày sneaker, giày thể thao, giày da nam",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop",
  },
];

// Hàm tạo mảng variants tiêu chuẩn
const makeVariants = (sizes, colors, stockRange = [5, 20]) => {
  const variants = [];
  for (const size of sizes) {
    for (const color of colors) {
      variants.push({
        size,
        color,
        stock: Math.floor(Math.random() * (stockRange[1] - stockRange[0] + 1)) + stockRange[0],
      });
    }
  }
  return variants;
};

const SIZES_TOP = ["S", "M", "L", "XL"];
const SIZES_BOTTOM = ["29", "30", "31", "32", "34"];
const SIZES_SHOE = ["39", "40", "41", "42", "43"];

const buildProducts = (categoryMap) => [
  // ===== MOCKUP TRANG CHỦ (4 sản phẩm) =====
  {
    name: "Kinetic Pulse Tee",
    slug: "kinetic-pulse-tee",
    description: "Áo thun streetwear thiết kế mạnh mẽ.",
    price: 450000,
    compareAtPrice: 550000,
    category: categoryMap["ao"],
    brand: "STREETWEAR",
    sku: "SW-KPT-01",
    images: ["https://content.jdmagicbox.com/quickquotes/images_main/men-s-round-neck-essential-solid-t-shirt-2223847936-w92243ke.png?impolicy=queryparam&im=Resize=(360,360),aspect=fit"],
    variants: makeVariants(SIZES_TOP, ["Urban Core", "Đen"]),
    material: "Cotton",
    careInstructions: "Giặt máy nhẹ",
    isFeatured: true,
  },
  {
    name: "Urban Nomad Cargo",
    slug: "urban-nomad-cargo",
    description: "Quần túi hộp thiết kế năng động.",
    price: 890000,
    compareAtPrice: 1100000,
    category: categoryMap["quan"],
    brand: "STREETWEAR",
    sku: "SW-UNC-01",
    images: ["https://5.imimg.com/data5/SELLER/Default/2022/9/XY/PP/IN/42079099/img-20220915-181156-500x500.jpg"],
    variants: makeVariants(SIZES_BOTTOM, ["Urban Core", "Xám"]),
    material: "Ripstop",
    careInstructions: "Không sấy",
    isFeatured: true,
  },
  {
    name: "Neon Signal Hoodie",
    slug: "neon-signal-hoodie",
    description: "Hoodie phát sáng ban đêm.",
    price: 720000,
    compareAtPrice: 0,
    category: categoryMap["hoodie-sweater"],
    brand: "STREETWEAR",
    sku: "SW-NSH-01",
    images: ["https://m.media-amazon.com/images/I/41K0p2rI4yS._SL500_.jpg"],
    variants: makeVariants(SIZES_TOP, ["Urban Core", "Xanh"]),
    material: "Nỉ bông",
    careInstructions: "Giặt tay",
    isFeatured: true,
  },
  {
    name: "District Sling Bag",
    slug: "district-sling-bag",
    description: "Túi chéo tiện dụng cho đường phố.",
    price: 380000,
    compareAtPrice: 0,
    category: categoryMap["phu-kien"],
    brand: "STREETWEAR",
    sku: "SW-DSB-01",
    images: ["https://m.media-amazon.com/images/I/71uAofBto2L._AC_UY1100_.jpg"],
    variants: [{ size: "ONE SIZE", color: "Urban Core", stock: 10 }],
    material: "Nylon",
    careInstructions: "Lau bề mặt",
    isFeatured: true,
  },

  // ===== MOCKUP SHOP PAGE (5 sản phẩm mới) =====
  {
    name: "Streetwear Graphic Tee",
    slug: "streetwear-graphic-tee",
    description: "Áo thun Graphic thiết kế đường phố bụi bặm, phá cách.",
    price: 350000,
    compareAtPrice: 450000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "SW-SGT-01",
    images: ["https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800"],
    variants: makeVariants(SIZES_TOP, ["Trắng", "Đen"]),
    material: "Cotton",
    careInstructions: "Giặt máy nhẹ",
    isFeatured: false,
  },
  {
    name: "Cargo Parachute Pants",
    slug: "cargo-parachute-pants",
    description: "Quần dù Parachute rộng rãi, cản gió nhẹ, hợp xu hướng SS24.",
    price: 650000,
    compareAtPrice: 800000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "SW-CPP-01",
    images: ["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=800"],
    variants: makeVariants(SIZES_BOTTOM, ["Đen", "Xám nhạt"]),
    material: "Nylon Parachute",
    careInstructions: "Không ủi nóng",
    isFeatured: true,
  },
  {
    name: "Oversized Washed Hoodie",
    slug: "oversized-washed-hoodie",
    description: "Hoodie form siêu rộng, hiệu ứng giặt wash nghệ thuật.",
    price: 850000,
    compareAtPrice: 1000000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "SW-OWH-01",
    images: ["https://images.unsplash.com/photo-1619603364904-c0498317e145?q=80&w=800"],
    variants: makeVariants(SIZES_TOP, ["Xám Wash", "Xanh đen"]),
    material: "Nỉ chân cua bông",
    careInstructions: "Giặt lộn trái",
    isFeatured: false,
  },
  {
    name: "Crossbody Tech Bag",
    slug: "crossbody-tech-bag",
    description: "Túi chéo phong cách Techwear đựng vừa ipad và vật dụng cá nhân.",
    price: 420000,
    compareAtPrice: 0,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "SW-CTB-01",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800"],
    variants: [{ size: "ONE SIZE", color: "Đen Tech", stock: 15 }],
    material: "Vải kháng nước",
    careInstructions: "Lau sạch bằng khăn",
    isFeatured: false,
  },
  {
    name: "Chunky Retro Sneaker",
    slug: "chunky-retro-sneaker",
    description: "Giày Sneaker Chunky đế cao tôn dáng, thiết kế hoài cổ.",
    price: 1350000,
    compareAtPrice: 1600000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "SW-CRS-01",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800"],
    variants: makeVariants(SIZES_SHOE, ["Trắng xám", "Đen"]),
    material: "Da lộn pha lưới",
    careInstructions: "Vệ sinh bọt chuyên dụng",
    isFeatured: true,
  },

  // ===== ÁO (6 sản phẩm) =====
  {
    name: "Áo Thun Pulse Drive",
    slug: "ao-thun-pulse-drive",
    description: "Áo thun cotton cao cấp với thiết kế tối giản, phù hợp mix đồ hằng ngày. Chất liệu mềm mịn, thoáng khí, form regular fit thoải mái.",
    price: 450000,
    compareAtPrice: 550000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AT-001",
    images: [
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_TOP, ["Đen", "Trắng", "Xám"]),
    material: "100% Cotton",
    careInstructions: "Giặt máy ở 30°C, không sử dụng chất tẩy, phơi trong bóng râm.",
    isFeatured: true,
  },
  {
    name: "Áo Polo Urban Classic",
    slug: "ao-polo-urban-classic",
    description: "Áo polo cổ bẻ sang trọng, chất pique dày dặn. Phù hợp đi làm, đi chơi hay sự kiện bán trang trọng.",
    price: 520000,
    compareAtPrice: 0,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AP-002",
    images: [
      "https://images.unsplash.com/photo-1625910513413-5fc42b4c1b53?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_TOP, ["Đen", "Navy", "Trắng"]),
    material: "Cotton Pique 220gsm",
    careInstructions: "Giặt máy ở 30°C, là ủi ở nhiệt độ thấp.",
    isFeatured: false,
  },
  {
    name: "Áo Sơ Mi Oxford Minimal",
    slug: "ao-so-mi-oxford-minimal",
    description: "Áo sơ mi Oxford dài tay, cổ button-down. Phong cách smart casual, dễ dàng tạo ấn tượng chuyên nghiệp nhưng vẫn trẻ trung.",
    price: 680000,
    compareAtPrice: 850000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AS-003",
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598032895455-1e67f0596889?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_TOP, ["Trắng", "Xanh nhạt"]),
    material: "Vải Oxford Cotton",
    careInstructions: "Giặt tay hoặc giặt máy nhẹ, là ủi ở nhiệt độ trung bình.",
    isFeatured: true,
  },
  {
    name: "Áo Thun Oversize Neon Tag",
    slug: "ao-thun-oversize-neon-tag",
    description: "Áo thun oversize với tag neon bắt mắt. Form rộng thoải mái, phong cách streetwear cá tính.",
    price: 390000,
    compareAtPrice: 0,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AT-004",
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_TOP, ["Đen", "Trắng"]),
    material: "Cotton French Terry 250gsm",
    careInstructions: "Giặt lộn mặt trong, giặt máy ở 30°C.",
    isFeatured: false,
  },

  // ===== QUẦN (3 sản phẩm) =====
  {
    name: "Quần Cargo Urban Core",
    slug: "quan-cargo-urban-core",
    description: "Quần cargo nhiều túi hộp phong cách techwear. Chất liệu ripstop bền bỉ, co giãn nhẹ, ống suông hiện đại.",
    price: 890000,
    compareAtPrice: 1100000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QC-001",
    images: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_BOTTOM, ["Đen", "Xám đậm", "Xanh rêu"]),
    material: "Ripstop Nylon pha Cotton",
    careInstructions: "Giặt máy ở 40°C, không sấy khô.",
    isFeatured: true,
  },
  {
    name: "Quần Jeans Slim Fit Dark",
    slug: "quan-jeans-slim-fit-dark",
    description: "Quần jeans slim fit wash tối. Chất denim dày dặn, co giãn vừa phải, tôn dáng cho phái mạnh.",
    price: 750000,
    compareAtPrice: 0,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QJ-002",
    images: [
      "https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_BOTTOM, ["Xanh đậm", "Đen"]),
    material: "Denim Cotton 98%, Spandex 2%",
    careInstructions: "Giặt lộn mặt trong, giặt riêng lần đầu, không sử dụng chất tẩy.",
    isFeatured: false,
  },
  {
    name: "Quần Short Khaki Relax",
    slug: "quan-short-khaki-relax",
    description: "Quần short khaki form relax fit. Chất vải kaki mềm, thoáng mát cho mùa hè năng động.",
    price: 450000,
    compareAtPrice: 550000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QS-003",
    images: [
      "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_BOTTOM, ["Be", "Đen", "Navy"]),
    material: "Cotton Twill",
    careInstructions: "Giặt máy ở 30°C, là ủi ở nhiệt độ thấp.",
    isFeatured: false,
  },

  // ===== HOODIE & SWEATER (3 sản phẩm) =====
  {
    name: "Hoodie Neon Signal",
    slug: "hoodie-neon-signal",
    description: "Hoodie nỉ bông dày dặn với in neon phát sáng. Mũ trùm có dây rút, túi kangaroo phía trước. Lựa chọn hoàn hảo cho mùa đông.",
    price: 720000,
    compareAtPrice: 900000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-HD-001",
    images: [
      "https://images.unsplash.com/photo-1619603364904-c0498317e145?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_TOP, ["Đen", "Xám", "Xanh navy"]),
    material: "French Terry 350gsm, lót nỉ bông",
    careInstructions: "Giặt máy ở 30°C, không sấy khô, phơi trong bóng râm.",
    isFeatured: true,
  },
  {
    name: "Sweater Crewneck Essential",
    slug: "sweater-crewneck-essential",
    description: "Áo sweater cổ tròn basic, chất nỉ mềm mịn. Thiết kế không logo, tối giản đúng chất minimalist.",
    price: 590000,
    compareAtPrice: 0,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-SW-002",
    images: [
      "https://images.unsplash.com/photo-1578681994506-b8f463449011?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_TOP, ["Đen", "Kem", "Nâu"]),
    material: "Cotton Fleece 300gsm",
    careInstructions: "Giặt máy nhẹ ở 30°C, không vắt, phơi nằm ngang.",
    isFeatured: false,
  },
  {
    name: "Zip Hoodie Techwear Pro",
    slug: "zip-hoodie-techwear-pro",
    description: "Hoodie kéo khóa phong cách techwear. Vải chống nước nhẹ, túi ngực tiện dụng, chi tiết phản quang.",
    price: 950000,
    compareAtPrice: 1200000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-ZH-003",
    images: [
      "https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_TOP, ["Đen", "Xám đậm"]),
    material: "Polyester chống nước DWR, lót mesh",
    careInstructions: "Giặt tay, không sử dụng chất tẩy, phơi khô tự nhiên.",
    isFeatured: true,
  },

  // ===== PHỤ KIỆN (2 sản phẩm) =====
  {
    name: "Balo Đen Techline",
    slug: "balo-den-techline",
    description: "Balo techwear dung tích 25L. Ngăn laptop 15.6 inch, chống nước, khóa kéo YKK, dây đai chắc chắn.",
    price: 380000,
    compareAtPrice: 480000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-BL-001",
    images: [
      "https://images.unsplash.com/photo-1581605405669-fcdf81165afa?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop",
    ],
    variants: [{ size: "ONE SIZE", color: "Đen", stock: 30 }],
    material: "Cordura Nylon 500D",
    careInstructions: "Lau bằng khăn ẩm, không giặt máy.",
    isFeatured: true,
  },
  {
    name: "Nón Bucket Urban",
    slug: "non-bucket-urban",
    description: "Nón bucket hai mặt với vành rộng che nắng. Chất liệu cotton thoáng khí, phù hợp hoạt động ngoài trời.",
    price: 250000,
    compareAtPrice: 0,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-NB-002",
    images: [
      "https://images.unsplash.com/photo-1588850561407-ed78c334e67a?q=80&w=800&auto=format&fit=crop",
    ],
    variants: [
      { size: "ONE SIZE", color: "Đen", stock: 25 },
      { size: "ONE SIZE", color: "Kem", stock: 15 },
    ],
    material: "Cotton Canvas",
    careInstructions: "Giặt tay nhẹ nhàng, phơi khô tự nhiên.",
    isFeatured: false,
  },

  // ===== GIÀY (2 sản phẩm) =====
  {
    name: "Sneaker Low-top Monochrome",
    slug: "sneaker-low-top-monochrome",
    description: "Giày sneaker cổ thấp phong cách tối giản. Đế cao su chống trượt, lót êm ái, phù hợp đi bộ cả ngày.",
    price: 1290000,
    compareAtPrice: 1500000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-SN-001",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_SHOE, ["Trắng", "Đen"]),
    material: "Da tổng hợp PU, đế cao su",
    careInstructions: "Lau bằng khăn ẩm, xịt chống thấm nước định kỳ.",
    isFeatured: true,
  },
  {
    name: "Giày Thể Thao Runner X",
    slug: "giay-the-thao-runner-x",
    description: "Giày chạy bộ công nghệ đệm khí. Trọng lượng nhẹ, thoáng khí, phù hợp tập gym và chạy bộ hằng ngày.",
    price: 1490000,
    compareAtPrice: 0,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-RX-002",
    images: [
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop",
    ],
    variants: makeVariants(SIZES_SHOE, ["Đen", "Trắng/Đen"]),
    material: "Mesh thoáng khí, đế EVA + cao su",
    careInstructions: "Lau bằng bàn chải mềm và nước ấm, phơi khô trong bóng râm.",
    isFeatured: false,
  },

  // ===== ÁO — 10 SẢN PHẨM BỔ SUNG =====
  {
    name: "Áo Thun Basic Essential",
    slug: "ao-thun-basic-essential",
    description: "Áo thun cotton basic không logo, form regular fit. Chất liệu mềm mịn thoáng khí, dễ phối đồ hằng ngày.",
    price: 280000,
    compareAtPrice: 0,
    costPrice: 129000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AT-005",
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Trắng", "Đen", "Xám"]),
    material: "100% Cotton 180gsm",
    careInstructions: "Giặt máy ở 30°C, không sử dụng chất tẩy.",
    isFeatured: false,
  },
  {
    name: "Áo Thun Racing Stripe",
    slug: "ao-thun-racing-stripe",
    description: "Áo thun sọc viền cổ cổ điển phong cách racing. Hai sọc màu tương phản nổi bật trên nền trắng tinh.",
    price: 320000,
    compareAtPrice: 400000,
    costPrice: 147000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AT-006",
    images: ["https://images.unsplash.com/photo-1503341504253-dff4815485f1?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Trắng/Đen", "Trắng/Đỏ"]),
    material: "Cotton Jersey 200gsm",
    careInstructions: "Giặt máy nhẹ, phơi trong bóng râm.",
    isFeatured: false,
  },
  {
    name: "Áo Polo Premium Stripe",
    slug: "ao-polo-premium-stripe",
    description: "Áo polo cổ bẻ chất pique mỏng nhẹ, hoạ tiết kẻ sọc tinh tế. Phù hợp dùng trong văn phòng hoặc dạo phố.",
    price: 490000,
    compareAtPrice: 620000,
    costPrice: 225000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AP-003",
    images: ["https://images.unsplash.com/photo-1625910513413-5fc42b4c1b53?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Trắng/Navy", "Đen/Xám"]),
    material: "Cotton Pique 200gsm",
    careInstructions: "Giặt máy ở 30°C, là ủi ở nhiệt độ thấp.",
    isFeatured: false,
  },
  {
    name: "Áo Sơ Mi Flannel Check",
    slug: "ao-so-mi-flannel-check",
    description: "Áo sơ mi vải flannel kẻ ô cổ điển. Giữ ấm nhẹ cho mùa se lạnh, có thể mặc ngoài áo thun.",
    price: 620000,
    compareAtPrice: 780000,
    costPrice: 285000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AS-004",
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Đỏ/Đen", "Xanh/Trắng"]),
    material: "Cotton Flannel 230gsm",
    careInstructions: "Giặt máy nhẹ ở 30°C, không sấy khô.",
    isFeatured: false,
  },
  {
    name: "Áo Thun Tie-Dye Wave",
    slug: "ao-thun-tie-dye-wave",
    description: "Áo thun tie-dye hoạ tiết sóng nước độc đáo, mỗi chiếc là một bản duy nhất. Làm điểm nhấn cho mọi outfit.",
    price: 350000,
    compareAtPrice: 0,
    costPrice: 161000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AT-007",
    images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Tím/Hồng", "Xanh/Vàng"]),
    material: "100% Cotton 200gsm",
    careInstructions: "Giặt tay lần đầu, sau đó giặt máy nhẹ.",
    isFeatured: false,
  },
  {
    name: "Áo Tank Street Urban",
    slug: "ao-tank-street-urban",
    description: "Áo ba lỗ vải cotton dày, form suông nhẹ. Phù hợp gym, đi biển hoặc layer dưới áo khoác.",
    price: 210000,
    compareAtPrice: 0,
    costPrice: 97000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AT-008",
    images: ["https://images.unsplash.com/photo-1532453288672-3a17ac36f101?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Đen", "Trắng"]),
    material: "Cotton Ribbed 200gsm",
    careInstructions: "Giặt máy ở 30°C, phơi ngang tránh biến dạng.",
    isFeatured: false,
  },
  {
    name: "Áo Khoác Bomber Basic",
    slug: "ao-khoac-bomber-basic",
    description: "Áo khoác bomber vải ngoài chống gió nhẹ, lót lưới thoáng mát. Cổ dệt, manchette và lai áo co giãn tạo dáng chuẩn.",
    price: 890000,
    compareAtPrice: 1100000,
    costPrice: 409000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AK-001",
    images: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Đen", "Olive"]),
    material: "Polyester Shell, lót Mesh",
    careInstructions: "Giặt tay nhẹ, không sấy khô.",
    isFeatured: true,
  },
  {
    name: "Áo Sơ Mi Oversize Denim",
    slug: "ao-so-mi-oversize-denim",
    description: "Áo sơ mi denim form oversize wash nhạt. Mặc như áo khoác ngoài áo thun hoặc buộc vạt tạo phong cách cá tính.",
    price: 720000,
    compareAtPrice: 900000,
    costPrice: 331000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AS-005",
    images: ["https://images.unsplash.com/photo-1598032895455-1e67f0596889?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Xanh nhạt", "Xanh đậm"]),
    material: "Denim Cotton 8oz",
    careInstructions: "Giặt lộn mặt trong ở 30°C, phơi ngang.",
    isFeatured: false,
  },
  {
    name: "Áo Thun Cropped Essential",
    slug: "ao-thun-cropped-essential",
    description: "Áo thun cropped vừa đủ gọn, phần gấu áo viền raw hem tạo điểm nhấn. Phối với quần cargo hoặc jogger rất ăn khớp.",
    price: 295000,
    compareAtPrice: 360000,
    costPrice: 136000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AT-009",
    images: ["https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Trắng", "Đen"]),
    material: "Cotton 200gsm",
    careInstructions: "Giặt máy ở 30°C, phơi trong bóng râm.",
    isFeatured: false,
  },
  {
    name: "Áo Polo Textured Pique",
    slug: "ao-polo-textured-pique",
    description: "Áo polo chất pique cấu trúc nổi bề mặt, tạo chiều sâu cho thiết kế tối giản. Cổ phẳng bẻ sang trọng.",
    price: 540000,
    compareAtPrice: 0,
    costPrice: 248000,
    category: categoryMap["ao"],
    brand: "VIBE URBAN",
    sku: "VU-AP-004",
    images: ["https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Be", "Navy", "Trắng gãy"]),
    material: "Cotton Pique Textured 230gsm",
    careInstructions: "Là ủi ở nhiệt độ trung bình, giặt máy nhẹ.",
    isFeatured: false,
  },

  // ===== QUẦN — 10 SẢN PHẨM BỔ SUNG =====
  {
    name: "Quần Jogger Essential",
    slug: "quan-jogger-essential",
    description: "Quần jogger cotton dày dặn với cạp chun dây rút, manchette chun gọn. Thoải mái mặc cả ngày, phù hợp nhiều hoàn cảnh.",
    price: 480000,
    compareAtPrice: 590000,
    costPrice: 211000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QJ-003",
    images: ["https://images.unsplash.com/photo-1519058082700-08a515d26aa7?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Đen", "Xám"]),
    material: "Cotton Fleece 300gsm",
    careInstructions: "Giặt máy ở 30°C, không sấy khô.",
    isFeatured: false,
  },
  {
    name: "Quần Kaki Straight Fit",
    slug: "quan-kaki-straight-fit",
    description: "Quần kaki ống thẳng cổ điển, chất cotton twill dày dặn. Phù hợp đi làm hoặc dạo phố cuối tuần.",
    price: 560000,
    compareAtPrice: 690000,
    costPrice: 246000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QK-001",
    images: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Be", "Đen", "Olive"]),
    material: "Cotton Twill 260gsm",
    careInstructions: "Giặt máy ở 40°C, là ủi cẩn thận.",
    isFeatured: false,
  },
  {
    name: "Quần Jeans Baggy Wash",
    slug: "quan-jeans-baggy-wash",
    description: "Quần jeans baggy ống rộng hiệu ứng wash nhạt theo xu hướng 90s. Eo trung, dáng suông tạo cảm giác thoải mái và phóng khoáng.",
    price: 720000,
    compareAtPrice: 890000,
    costPrice: 317000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QJ-004",
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Xanh nhạt", "Xanh đậm"]),
    material: "Denim Cotton 10oz",
    careInstructions: "Giặt lộn mặt trong ở 30°C, không sử dụng máy sấy.",
    isFeatured: true,
  },
  {
    name: "Quần Short Cargo Tactical",
    slug: "quan-short-cargo-tactical",
    description: "Quần short cargo với nhiều túi tiện dụng kiểu tactical. Vải ripstop chắc bền, dây rút gấu tạo dáng gọn.",
    price: 450000,
    compareAtPrice: 550000,
    costPrice: 198000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QS-004",
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Đen", "Olive", "Xám"]),
    material: "Ripstop Nylon Cotton",
    careInstructions: "Giặt máy ở 40°C, không ủi phần in.",
    isFeatured: false,
  },
  {
    name: "Quần Track Pants Retro",
    slug: "quan-track-pants-retro",
    description: "Quần thể thao track pants sọc bên hông phong cách retro thập niên 90. Chất nỉ bóng, cảm giác nhẹ và êm.",
    price: 530000,
    compareAtPrice: 650000,
    costPrice: 233000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QT-001",
    images: ["https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Đen/Trắng", "Navy/Đỏ"]),
    material: "Polyester Track 150gsm",
    careInstructions: "Giặt máy nhẹ, phơi khô tự nhiên.",
    isFeatured: false,
  },
  {
    name: "Quần Jeans Tapered Slim",
    slug: "quan-jeans-tapered-slim",
    description: "Quần jeans tapered ống hơi thon dần từ đùi xuống cổ chân. Dáng ôm vừa phải, tôn dáng nhưng không bó.",
    price: 680000,
    compareAtPrice: 0,
    costPrice: 299000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QJ-005",
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Xanh indigo", "Đen"]),
    material: "Denim Cotton Stretch 11oz",
    careInstructions: "Giặt ở 30°C, không sấy, phơi ngược.",
    isFeatured: false,
  },
  {
    name: "Quần Cargo Ripstop Heavy",
    slug: "quan-cargo-ripstop-heavy",
    description: "Quần cargo vải ripstop nặng đô, 6 túi thực dụng với khoá bấm. Phù hợp cả đi làm công trường lẫn phong cách streetwear cứng.",
    price: 790000,
    compareAtPrice: 990000,
    costPrice: 348000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QC-002",
    images: ["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Đen", "Xám đậm"]),
    material: "Ripstop Cotton 300gsm",
    careInstructions: "Giặt máy ở 40°C, không sấy.",
    isFeatured: true,
  },
  {
    name: "Quần Short Denim Frayed",
    slug: "quan-short-denim-frayed",
    description: "Quần short denim gấu tua rua raw hem tạo cảm giác vintage phóng khoáng. Wash nhạt tự nhiên.",
    price: 380000,
    compareAtPrice: 460000,
    costPrice: 167000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QS-005",
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Xanh nhạt"]),
    material: "Denim Cotton 8oz",
    careInstructions: "Giặt lộn mặt trong, không sấy.",
    isFeatured: false,
  },
  {
    name: "Quần Wide Leg Linen",
    slug: "quan-wide-leg-linen",
    description: "Quần ống rộng chất linen thoáng mát cho mùa hè. Cạp thun dây rút, dáng suông bay bổng.",
    price: 650000,
    compareAtPrice: 800000,
    costPrice: 286000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QW-001",
    images: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Beige", "Đen", "Trắng"]),
    material: "Linen 55%, Cotton 45%",
    careInstructions: "Giặt tay hoặc giặt máy nhẹ ở 30°C.",
    isFeatured: false,
  },
  {
    name: "Quần Jogger Techwear Slim",
    slug: "quan-jogger-techwear-slim",
    description: "Quần jogger phong cách techwear với đường may nổi, túi kéo khóa ẩn, chất polyester co giãn 4 chiều.",
    price: 590000,
    compareAtPrice: 730000,
    costPrice: 260000,
    category: categoryMap["quan"],
    brand: "VIBE URBAN",
    sku: "VU-QJ-006",
    images: ["https://images.unsplash.com/photo-1519058082700-08a515d26aa7?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_BOTTOM, ["Đen"]),
    material: "Polyester Stretch 4 chiều",
    careInstructions: "Giặt máy nhẹ, không ủi.",
    isFeatured: false,
  },

  // ===== HOODIE & SWEATER — 10 SẢN PHẨM BỔ SUNG =====
  {
    name: "Hoodie Unisex Basic",
    slug: "hoodie-unisex-basic",
    description: "Hoodie nỉ bông basic không logo. Mũ trùm có dây rút, túi kangaroo, form rộng thoải mái.",
    price: 580000,
    compareAtPrice: 720000,
    costPrice: 290000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-HD-004",
    images: ["https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Đen", "Trắng", "Xám"]),
    material: "French Terry Cotton 320gsm",
    careInstructions: "Giặt máy ở 30°C, phơi trong bóng râm.",
    isFeatured: false,
  },
  {
    name: "Zip Hoodie Essential Grey",
    slug: "zip-hoodie-essential-grey",
    description: "Hoodie kéo khóa chất cotton fleece. Khóa YKK hai chiều, túi có khoá. Phối tốt với mọi outfit.",
    price: 650000,
    compareAtPrice: 0,
    costPrice: 325000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-ZH-004",
    images: ["https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Xám nhạt", "Đen"]),
    material: "Cotton Fleece 300gsm",
    careInstructions: "Giặt máy nhẹ, không sấy khô.",
    isFeatured: false,
  },
  {
    name: "Sweater Oversized Cream",
    slug: "sweater-oversized-cream",
    description: "Áo sweater oversize màu kem trung tính. Cổ rộng, tay dài, chất dày giữ ấm nhẹ nhàng.",
    price: 680000,
    compareAtPrice: 840000,
    costPrice: 340000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-SW-003",
    images: ["https://images.unsplash.com/photo-1578681994506-b8f463449011?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Kem", "Be"]),
    material: "Cotton Waffle Knit 280gsm",
    careInstructions: "Giặt tay nhẹ, phơi nằm ngang.",
    isFeatured: false,
  },
  {
    name: "Hoodie Acid Wash Drop",
    slug: "hoodie-acid-wash-drop",
    description: "Hoodie hiệu ứng acid wash tạo màu sắc pha trộn độc đáo. Drop shoulder form rộng cá tính.",
    price: 780000,
    compareAtPrice: 960000,
    costPrice: 390000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-HD-005",
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Đen acid", "Xanh acid"]),
    material: "French Terry 350gsm",
    careInstructions: "Giặt lộn trái ở 30°C, không sấy.",
    isFeatured: true,
  },
  {
    name: "Crewneck Minimal White",
    slug: "crewneck-minimal-white",
    description: "Áo crewneck cổ tròn trắng tối giản. Không logo, không hoạ tiết — đơn giản nhưng sang.",
    price: 490000,
    compareAtPrice: 610000,
    costPrice: 245000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-CN-001",
    images: ["https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Trắng", "Kem", "Xám nhạt"]),
    material: "Cotton Fleece 280gsm",
    careInstructions: "Giặt máy ở 30°C, không dùng chất tẩy.",
    isFeatured: false,
  },
  {
    name: "Hoodie Stadium Coach",
    slug: "hoodie-stadium-coach",
    description: "Hoodie phong cách coach jacket, cổ cao bọc chắn gió. Phù hợp dùng khi trời se lạnh hoặc layering.",
    price: 820000,
    compareAtPrice: 1020000,
    costPrice: 410000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-HD-006",
    images: ["https://images.unsplash.com/photo-1619603364904-c0498317e145?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Navy", "Đen"]),
    material: "Nylon Shell, lót Cotton",
    careInstructions: "Giặt tay nhẹ, phơi khô tự nhiên.",
    isFeatured: false,
  },
  {
    name: "Sweater Ribknit Camel",
    slug: "sweater-ribknit-camel",
    description: "Áo sweater chất len đan sườn (ribknit) co giãn ôm vừa người. Màu camel ấm áp, sang trọng cho mùa thu đông.",
    price: 720000,
    compareAtPrice: 0,
    costPrice: 360000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-SW-004",
    images: ["https://images.unsplash.com/photo-1578681994506-b8f463449011?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Camel", "Đen", "Nâu đất"]),
    material: "Acrylic Wool 60%, Cotton 40%",
    careInstructions: "Giặt tay nhẹ ở 20°C, phơi nằm ngang.",
    isFeatured: true,
  },
  {
    name: "Hoodie Graphic Block",
    slug: "hoodie-graphic-block",
    description: "Hoodie in họa tiết block color phủ toàn áo, tạo điểm nhấn bold statement. Form regular.",
    price: 750000,
    compareAtPrice: 920000,
    costPrice: 375000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-HD-007",
    images: ["https://images.unsplash.com/photo-1511631127986-f9a37d3a2c9a?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Đen/Vàng", "Đen/Đỏ"]),
    material: "French Terry Cotton 320gsm",
    careInstructions: "Giặt lộn trái, nhiệt độ thấp.",
    isFeatured: false,
  },
  {
    name: "Pullover Fleece Comfort",
    slug: "pullover-fleece-comfort",
    description: "Áo pullover lông cừu nhân tạo (polar fleece) siêu nhẹ siêu ấm. Không có mũ, cổ tròn, dễ mặc.",
    price: 630000,
    compareAtPrice: 780000,
    costPrice: 315000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-PL-001",
    images: ["https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Xám nhạt", "Đen", "Xanh đậm"]),
    material: "Polar Fleece 200gsm",
    careInstructions: "Giặt máy nhẹ, không sấy.",
    isFeatured: false,
  },
  {
    name: "Sweatshirt Emboss Logo",
    slug: "sweatshirt-emboss-logo",
    description: "Áo sweatshirt với logo Vibe Urban dập nổi 3D tinh tế. Không cần họa tiết phô trương mà vẫn nhận ra ngay.",
    price: 560000,
    compareAtPrice: 0,
    costPrice: 280000,
    category: categoryMap["hoodie-sweater"],
    brand: "VIBE URBAN",
    sku: "VU-SS-001",
    images: ["https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_TOP, ["Đen", "Trắng"]),
    material: "Cotton Fleece 300gsm",
    careInstructions: "Giặt máy ở 30°C, lộn trái.",
    isFeatured: false,
  },

  // ===== PHỤ KIỆN — 10 SẢN PHẨM BỔ SUNG =====
  {
    name: "Túi Tote Canvas Urban",
    slug: "tui-tote-canvas-urban",
    description: "Túi tote vải canvas dày 12oz. Quai xách chắc chắn, dung tích lớn đựng laptop 13 inch và đồ cá nhân.",
    price: 290000,
    compareAtPrice: 0,
    costPrice: 110000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-TT-001",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop"],
    variants: [
      { size: "ONE SIZE", color: "Đen", stock: 30 },
      { size: "ONE SIZE", color: "Kem", stock: 20 },
    ],
    material: "Canvas Cotton 12oz",
    careInstructions: "Giặt tay nhẹ, phơi khô tự nhiên.",
    isFeatured: false,
  },
  {
    name: "Ví Da Slim Bifold",
    slug: "vi-da-slim-bifold",
    description: "Ví da thật bifold siêu mỏng chỉ 8mm. Ngăn thẻ RFID-blocking, ngăn tiền mặt tiện lợi.",
    price: 380000,
    compareAtPrice: 480000,
    costPrice: 144000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-VD-001",
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop"],
    variants: [
      { size: "ONE SIZE", color: "Đen", stock: 25 },
      { size: "ONE SIZE", color: "Nâu", stock: 20 },
    ],
    material: "Da thật Cowhide Grain",
    careInstructions: "Lau nhẹ bằng vải mềm, dưỡng da định kỳ.",
    isFeatured: false,
  },
  {
    name: "Mũ Dad Hat Washed",
    slug: "mu-dad-hat-washed",
    description: "Mũ dad hat vải cotton wash mềm vành cong tự nhiên. Khoá kim loại sau, điều chỉnh kích thước dễ dàng.",
    price: 220000,
    compareAtPrice: 0,
    costPrice: 84000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-MH-001",
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c334e67a?q=80&w=800&auto=format&fit=crop"],
    variants: [
      { size: "ONE SIZE", color: "Xám wash", stock: 20 },
      { size: "ONE SIZE", color: "Đen", stock: 25 },
      { size: "ONE SIZE", color: "Nâu", stock: 15 },
    ],
    material: "Cotton Canvas Washed",
    careInstructions: "Giặt tay nhẹ, định hình vành trước khi phơi.",
    isFeatured: false,
  },
  {
    name: "Thắt Lưng Canvas Clip",
    slug: "that-lung-canvas-clip",
    description: "Thắt lưng vải canvas với khoá clip nhôm nhẹ. Điều chỉnh dễ dàng, không cần đục lỗ.",
    price: 180000,
    compareAtPrice: 0,
    costPrice: 68000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-TL-001",
    images: ["https://images.unsplash.com/photo-1611186871525-6c77ea3bfe9d?q=80&w=800&auto=format&fit=crop"],
    variants: [
      { size: "ONE SIZE", color: "Đen", stock: 40 },
      { size: "ONE SIZE", color: "Olive", stock: 20 },
    ],
    material: "Canvas Cotton, khoá nhôm",
    careInstructions: "Lau bằng khăn ẩm.",
    isFeatured: false,
  },
  {
    name: "Kính Mát Rectangle Flat",
    slug: "kinh-mat-rectangle-flat",
    description: "Kính mát tròng hình chữ nhật dẹt, gọng kim loại mỏng. Tròng chống tia UV400.",
    price: 320000,
    compareAtPrice: 420000,
    costPrice: 122000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-KM-001",
    images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=800&auto=format&fit=crop"],
    variants: [
      { size: "ONE SIZE", color: "Đen", stock: 20 },
      { size: "ONE SIZE", color: "Vàng đồng", stock: 15 },
    ],
    material: "Gọng kim loại, tròng polycarbonate UV400",
    careInstructions: "Lau bằng vải microfiber, tránh nơi nhiệt độ cao.",
    isFeatured: false,
  },
  {
    name: "Túi Messenger Nylon",
    slug: "tui-messenger-nylon",
    description: "Túi messenger nylon dung tích vừa, ngăn laptop 13 inch. Dây đeo có đệm vai, khoá từ tiện lợi.",
    price: 450000,
    compareAtPrice: 560000,
    costPrice: 171000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-TM-001",
    images: ["https://images.unsplash.com/photo-1581605405669-fcdf81165afa?q=80&w=800&auto=format&fit=crop"],
    variants: [{ size: "ONE SIZE", color: "Đen", stock: 20 }],
    material: "Nylon 600D kháng nước",
    careInstructions: "Lau bằng khăn ẩm, không giặt máy.",
    isFeatured: false,
  },
  {
    name: "Nón 5-Panel Camp",
    slug: "non-5-panel-camp",
    description: "Nón 5-panel kiểu camp cap phong cách outdoor. Vành cứng phẳng, lưới sau thoáng mát.",
    price: 250000,
    compareAtPrice: 0,
    costPrice: 95000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-N5-001",
    images: ["https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?q=80&w=800&auto=format&fit=crop"],
    variants: [
      { size: "ONE SIZE", color: "Đen", stock: 25 },
      { size: "ONE SIZE", color: "Be", stock: 20 },
      { size: "ONE SIZE", color: "Xanh lá", stock: 15 },
    ],
    material: "Cotton 6-panel, lưới polyester",
    careInstructions: "Giặt tay nhẹ, định hình trước khi phơi.",
    isFeatured: false,
  },
  {
    name: "Túi Clutch Nylon Urban",
    slug: "tui-clutch-nylon-urban",
    description: "Túi clutch vải nylon tiện dụng khi đi chơi tối. Khoá kéo YKK, đủ chứa điện thoại, thẻ và chìa khoá.",
    price: 280000,
    compareAtPrice: 0,
    costPrice: 106000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-TC-001",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop"],
    variants: [
      { size: "ONE SIZE", color: "Đen", stock: 25 },
      { size: "ONE SIZE", color: "Olive", stock: 15 },
    ],
    material: "Nylon Ripstop",
    careInstructions: "Lau bằng khăn ẩm sạch.",
    isFeatured: false,
  },
  {
    name: "Dây Cổ Layer Chain",
    slug: "day-co-layer-chain",
    description: "Dây cổ kiểu xích thinchain mỏng, có thể đeo nhiều tầng. Khoá tôm điều chỉnh độ dài.",
    price: 150000,
    compareAtPrice: 0,
    costPrice: 57000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-DC-001",
    images: ["https://images.unsplash.com/photo-1611186871525-6c77ea3bfe9d?q=80&w=800&auto=format&fit=crop"],
    variants: [
      { size: "ONE SIZE", color: "Bạc", stock: 30 },
      { size: "ONE SIZE", color: "Vàng", stock: 20 },
    ],
    material: "Thép không gỉ mạ",
    careInstructions: "Tránh tiếp xúc nước thường xuyên.",
    isFeatured: false,
  },
  {
    name: "Balo Mini Daypack",
    slug: "balo-mini-daypack",
    description: "Balo mini dung tích 12L, gọn nhẹ cho ngày đi chơi. Ngăn chính + ngăn phụ có khoá, quai có đệm.",
    price: 420000,
    compareAtPrice: 520000,
    costPrice: 160000,
    category: categoryMap["phu-kien"],
    brand: "VIBE URBAN",
    sku: "VU-BL-002",
    images: ["https://images.unsplash.com/photo-1581605405669-fcdf81165afa?q=80&w=800&auto=format&fit=crop"],
    variants: [
      { size: "ONE SIZE", color: "Đen", stock: 20 },
      { size: "ONE SIZE", color: "Xám", stock: 15 },
    ],
    material: "Polyester 600D kháng nước",
    careInstructions: "Lau bề mặt bằng khăn ẩm.",
    isFeatured: false,
  },

  // ===== GIÀY — 10 SẢN PHẨM BỔ SUNG =====
  {
    name: "Giày Chelsea Boot Da",
    slug: "giay-chelsea-boot-da",
    description: "Giày chelsea boot da thật cổ điển. Gioăng đàn hồi hai bên dễ mang, đế da khâu Blake tăng độ bền.",
    price: 1650000,
    compareAtPrice: 2050000,
    costPrice: 858000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-CB-001",
    images: ["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Đen", "Nâu"]),
    material: "Da thật full grain, đế cao su",
    careInstructions: "Đánh xi định kỳ, tránh ngâm nước.",
    isFeatured: true,
  },
  {
    name: "Giày Loafer Da Minimal",
    slug: "giay-loafer-da-minimal",
    description: "Giày loafer da lịch lãm với thiết kế cực tối giản. Không có bit hóa khóa, phù hợp cả đi làm lẫn dạo phố.",
    price: 1390000,
    compareAtPrice: 0,
    costPrice: 723000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-LF-001",
    images: ["https://images.unsplash.com/photo-1600269452121-4f2416e55c28?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Đen", "Be"]),
    material: "Da lộn nubuck, đế cao su",
    careInstructions: "Dùng xịt chống thấm, không giặt.",
    isFeatured: false,
  },
  {
    name: "Dép Slide Foam Comfort",
    slug: "dep-slide-foam-comfort",
    description: "Dép slide quai ngang đế EVA foam êm ái. Nhẹ và thoáng, đi biển hay ở nhà đều tuyệt.",
    price: 350000,
    compareAtPrice: 420000,
    costPrice: 182000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-SL-001",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Đen", "Trắng"]),
    material: "Đế EVA, quai PU",
    careInstructions: "Rửa bằng nước sạch, phơi nơi thoáng mát.",
    isFeatured: false,
  },
  {
    name: "Giày Oxford Minimal White",
    slug: "giay-oxford-minimal-white",
    description: "Giày oxford trắng tối giản cổ thấp. Đường may sạch sẽ, mũi vuông nhẹ tôn vẻ lịch lãm hiện đại.",
    price: 1250000,
    compareAtPrice: 1550000,
    costPrice: 650000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-OX-001",
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Trắng", "Đen"]),
    material: "Da tổng hợp PU cao cấp, đế cao su",
    careInstructions: "Lau sạch sau mỗi lần mang, tránh chỗ ẩm.",
    isFeatured: false,
  },
  {
    name: "Giày High-top Canvas",
    slug: "giay-high-top-canvas",
    description: "Giày cổ cao vải canvas kiểu All-Star cổ điển. Đế cao su lưu hoá, gót cứng, lót êm.",
    price: 890000,
    compareAtPrice: 1090000,
    costPrice: 463000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-HT-001",
    images: ["https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Trắng", "Đen", "Đỏ"]),
    material: "Canvas Cotton, đế cao su lưu hoá",
    careInstructions: "Giặt tay bằng bàn chải mềm, không sấy.",
    isFeatured: true,
  },
  {
    name: "Giày Slip-on Suede Grey",
    slug: "giay-slip-on-suede-grey",
    description: "Giày slip-on da lộn xám mềm mại. Đế Waffle đặc trưng phong cách skate, co giãn phần miệng giày tiện mang.",
    price: 980000,
    compareAtPrice: 1190000,
    costPrice: 510000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-SO-001",
    images: ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Xám", "Đen"]),
    material: "Da lộn suede, đế cao su Waffle",
    careInstructions: "Dùng bàn chải lông mềm làm sạch, xịt chống thấm định kỳ.",
    isFeatured: false,
  },
  {
    name: "Giày Derby Classic Brown",
    slug: "giay-derby-classic-brown",
    description: "Giày derby da nâu cổ điển với đường broguing tinh tế. Bền đẹp theo năm tháng, phù hợp công sở hoặc dạo phố.",
    price: 1450000,
    compareAtPrice: 1790000,
    costPrice: 754000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-DB-001",
    images: ["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Nâu", "Đen"]),
    material: "Da thật smooth grain, đế leather + cao su",
    careInstructions: "Đánh xi và dưỡng ẩm định kỳ.",
    isFeatured: false,
  },
  {
    name: "Giày Mule Da Nappa",
    slug: "giay-mule-da-nappa",
    description: "Giày mule (hở gót) da nappa mềm mịn kiểu backless loafer. Hiện đại, tiện lợi khi ra ngoài nhanh.",
    price: 1180000,
    compareAtPrice: 0,
    costPrice: 614000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-ML-001",
    images: ["https://images.unsplash.com/photo-1600269452121-4f2416e55c28?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Nâu", "Đen"]),
    material: "Da Nappa mềm, đế cao su",
    careInstructions: "Lau nhẹ bằng vải khô, dưỡng da định kỳ.",
    isFeatured: false,
  },
  {
    name: "Giày Platform Chunky Low",
    slug: "giay-platform-chunky-low",
    description: "Giày platform đế chunky dày 4cm cổ thấp. Tôn dáng hiệu quả, phối đẹp với skinny jeans hoặc jogger.",
    price: 1390000,
    compareAtPrice: 1690000,
    costPrice: 723000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-PF-001",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Trắng", "Đen"]),
    material: "Da tổng hợp PU, đế TPU chunky",
    careInstructions: "Lau bằng khăn ẩm, tránh ngâm nước.",
    isFeatured: true,
  },
  {
    name: "Dép Sandal Strap Leather",
    slug: "dep-sandal-strap-leather",
    description: "Sandal quai da với 2 dây cài khóa kim loại điều chỉnh. Đế da hơi gót chắc chân, phù hợp đi cả ngày.",
    price: 580000,
    compareAtPrice: 720000,
    costPrice: 302000,
    category: categoryMap["giay"],
    brand: "VIBE URBAN",
    sku: "VU-SD-001",
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop"],
    variants: makeVariants(SIZES_SHOE, ["Nâu", "Đen"]),
    material: "Da thật, đế cao su",
    careInstructions: "Lau khô ngay khi dính nước, tránh nơi ẩm.",
    isFeatured: false,
  },
];

// ====== MAIN SEEDER ======
const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_CONNECTIONSTRING);
    console.log("✅ Kết nối CSDL thành công!");

    // Xóa dữ liệu cũ
    await Category.deleteMany({});
    await Product.deleteMany({});
    console.log("🗑️  Đã xóa dữ liệu cũ (Categories & Products)");

    // Tạo categories
    const createdCategories = await Category.insertMany(CATEGORIES);
    console.log(`📁 Đã tạo ${createdCategories.length} danh mục`);

    // Tạo map slug → ObjectId
    const categoryMap = {};
    createdCategories.forEach((cat) => {
      categoryMap[cat.slug] = cat._id;
    });

    // Tạo products
    const productsData = buildProducts(categoryMap);
    const createdProducts = await Product.insertMany(productsData);
    console.log(`📦 Đã tạo ${createdProducts.length} sản phẩm`);

    // Tổng kết
    const featuredCount = createdProducts.filter((p) => p.isFeatured).length;
    console.log(`⭐ Trong đó ${featuredCount} sản phẩm nổi bật (isFeatured)`);

    // Re-seed combo để đồng bộ product ID mới
    console.log("\n── Đồng bộ combo ──────────────────────────────────");
    await seedCombos();
    console.log("\n🎉 Seed dữ liệu hoàn tất!");

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error("❌ Lỗi khi seed dữ liệu:", error);
    await mongoose.disconnect();
    process.exit(1);
  }
};

seedProducts();
